### ISSUE TITLE
Handle out-of-bounds initialization

### ISSUE THREAD

**Issue by AugustePaoli99** [JuliaExtremes/IDFCurves.jl#144]
Dans la méthode `fit_mle()`, il est possible que le vecteur `initialvalues` possède des valeurs physiquement impossibles. Dans ce cas l'appel `θ₀ = map_to_real_space(pd, initialvalues)` va créer une erreur. je propose de gérer ce problème de deux manières différentes :

- Dans le corps de la méthode `fit_mle()`, a moment de l'appel `θ₀ = map_to_real_space(pd, initialvalues)`, on va `try/catch` une possible erreur et renvoyer un message d'erreur personnalisé. Cela permettra de gérer le cas où l'utilisateur rentre un mauvais vecteur initial.
- Dans les différentes méthodes `initialize()`, on va s'assurer que l'initialisation automatique ne puisse jamais occasionner cette erreur. Pour cela, à l'issue de l'initialisation automatique, au lieu de renvoyer `α` (par exemple), on va renvoyer `maximum(0.01, minimum(0.99, α))`.

**Comment by AugustePaoli99** [comment]
@jojal5 ca te concient comme stratégie ? C'est de toutes façons assez marginal, mais de tels bugs peuvent finir par arriver notamment lors d'une étude de simulation par exemple.

**Comment by jojal5** [comment]
La deuxième option est la meilleure. C’est mieux de gérer le problème dans la fonction initialize()

**Comment by AugustePaoli99** [comment]
Oui, la première méthode est une assurance supplémentaire au cas où l'utilisateur spécifie lui-même l'initialisation et en propose une impossible.

**Comment by AugustePaoli99** [comment]
J'ai fait les modifs dans la branche consacrée.
1) J'ai enlevé la transformation du paramètre $\xi$ qui le forçait entre -1/2 et 1/2. Je ne sais même plus pourquoi on faisait ça initialement (ça vient de l'époque où je faisais du bayésien)
2) J'ai ajouté des `@assert` dans les méthodes `map_to_real_space()` qui vérifie que les paramètres sont dans les bons domaines. Ca permet de renvoyer tout de suite un message d'erreur clair si l'utilisateur initialise mal.
3) J'ai ajouté des `maximum(0.001, x)` et `minimum(0.999, x)` dans les méthodes d'initialisation automatique qui assurent l'absence d'erreur numérique.
