### ISSUE TITLE
Better if only one MaxLikelhoodEstimation function ?

### ISSUE THREAD

**Issue by AugustePaoli99** [JuliaExtremes/IDFCurves.jl#30]
I think it would be good to use the `DependentScalingModel` structure as a standard. The function `fit_mle(::DependentScalingModel)` would be extensively implemented. The function `fit_mle(::AbstractScalingModel)` could call `fit_mle(::DependentScalingModel)` after creating a `DependentScalingModel` with "identity" copula.

**Comment by jojal5** [comment]
I agree.

**Comment by AugustePaoli99** [comment]
Je viens de commit une première version. Tout fonctionne. Il me reste à redéfinir la méthode fit_mle(::MarginalScaling) en faisant appel à la méthode fit_mle(::DependentScaling) (note pour moi même)

**Comment by AugustePaoli99** [comment]
Ca y est j'ai une version stable. Je vais clore cette issue. Cependant il restera quelques détails à régler : 
- le problème d'initialisation qui est probablement l'idée à la question d'une optimisation avec ou sans gradient : c'est dans [l'issue 28](https://github.com/JuliaExtremes/IDFCurves.jl/issues/28)
- redéfinir la méthode hessian(:DependentScalingModel) : nouvelle issue [issue 65](https://github.com/JuliaExtremes/IDFCurves.jl/issues/65)
- plus tard, regarder à quel point tout cela est naturel d'un point de vue interface utilisateur
