### ISSUE TITLE
Macro refactorisation

### ISSUE THREAD

**Issue by AugustePaoli99** [JuliaExtremes/IDFCurves.jl#31]
In the folder _Structures_, I would change the names of the 4 sub-folders : 
- _CorrelationStructure_
- _MarginalScalingModel_
- _DependentScalingModel_
- _EllipticalCopula_

The folder _CorrelationStructure_ would contain 3 files, namely : 
- _abstractcorrelationstructure.jl_, in which the abstract type is implemented
- _exponentialcorrelationstructure.jl_
- _materncorrelationstructure.jl_

The folder _MarginalScalingModel_ would contain 3 files, namely : 
- _abstractmarginalscalingmodel.jl_, in which the abstract type is implemented
- _simplescalingmodel.jl_
- _dGEVmodel.jl_ (**should it be changed to general scaling ???**)

The folder _DependentScalingModel_ would contain 1 file, namely _dependentscalingmodel.jl_

The folder _EllipticalCopula_ would contain 3 files, namely : 
- _abstractellipticalcopula.jl_, in which the abstract type is implemented
- _gaussiancopula.jl_
- _Tcopula.jl_

**Comment by jojal5** [comment]
I agree !

**Comment by AugustePaoli99** [comment]
@jojal5 et pour ce qui est de changer `dGEV` pour `GeneralScaling` ?

**Comment by jojal5** [comment]
Je suis d'accord aussi.

**Comment by AugustePaoli99** [comment]
@jojal5 J'ai push dans la branche liée puis merge dans dev. Pour le moment les deux objets qui héritent de la classe abstraite `MarginalScalingModel` se nomment `SimpleScaling` et `GeneralScaling` respectivement. Mais j'ai un doute, serait-ce mieux s'ils s'appelaient `SimpleScalingModel` et `GeneralScalingModel` par exemple ?

**Comment by jojal5** [comment]
Je pense que c'est ok, je n'ai pas vu de guidelines spécifiquement sur la nomenclature des types concrets. Je sais cependant que les abstract types devraient être spécifiques, par exemple AbstractScalingModel plutôt que Scaling.
