### ISSUE TITLE
plotting IDF curves not based on data

### ISSUE THREAD

**Issue by AugustePaoli99** [JuliaExtremes/IDFCurves.jl#61]
For now all the methods written in _plots.jl_ for plotting IDF curves have an argument `data::IDFdata`. Confidence intervals are represented on the plot, based on the data. 
Should one be able to plot IDF curves based on a purely theoretical IDF scaling model ? Hence should the argument `data` be made optional ?

**Comment by jojal5** [comment]
Bonne idée. Pourrait-on penser à une fonction idfplot(model::AbstractScalingModel) ?

**Comment by AugustePaoli99** [comment]
Oui ! Remarque qu'il n'existe plus de type `AbstractScalingModel` qui a été remplacé par `MarginalScalingModel`. On peut en effet définir 2 méthodes : `idfplot(model::MarginalScalingModel)` et `idfplot(model::DependentScalingModel)`, ou bien on peut définir seulement `idfplot(model::DependentScalingModel)` et dire qu'un `MarginalScalingModel` est un `DependentScalingModel` avec copule identité (cf. @[issue 30](https://github.com/JuliaExtremes/IDFCurves.jl/issues/30))

**Comment by AugustePaoli99** [comment]
@jojal5, comment imagines-tu le tracé des courbes IDF ? Quelque chose qui ressmble à ce que j'avais fait dans _IDF.jl_ (cf figures de l'article) ? Dans le cas où on trace des courbes IDF provenant d'une estimation de paramètres : 
- Devrait-on pouvoir représenter les courbes correspondant aux intervalles de confiance ?
- Devrait-on pouvoir représenter les estimations ponctuelles par des croix ? Ainsi qu'éventuellement les intervalles de confiance correspondant à ces estimations ?

**Comment by jojal5** [comment]
Les figures du manuscrit sont parfaites. Ça devrait être la fonction par défaut. 

Les fonctionnalités additionnelles concernant les intervalles de confiance pourraient être possibles mais optionnelles car elles surcharges les figures. Dans le cas où les intervalles de confiance sont tracés (à la demande de l'utilisateur), il devrait choisir les période de retour pour ne pas surcharger les figures.

**Comment by AugustePaoli99** [comment]
J'ai fait les fonctions de base dans plots.jl et les ai ajoutées dans dev. Pour les fonctionnalités additionnelles (intervalles de confiance...) je vais créer une nouvelle branche.

**Comment by AugustePaoli99** [comment]
J'ai une première version du code qui me semble satisfaisante. Les fonctionnalités que l'on désirait sont implémentées. Cependant je ne suis pas sûr de la structure, tu pourras me dire ce que tu en penses ?

En gros la fonction principale est `plotIDFCurves()`. Il y a deux méthodes, `plotIDFCurves(model::DependentScalingModel; ...)` et `plotIDFCurves(model::DependentScalingModel, data::IDFdata; ...)`. Les arguments optionnels concernent les période de retour et les durées d'accumulation pour lesquelles on veut représenter la courbe. Pour la deuxième méthode, il y a également un argument optionnel `show_confidence_intervals`.

La première méthode fait appel à la fonction `get_layers_IDFCurves(model::DependentScalingModel, T_values::Vector{<:Real}, durations_range::Vector{<:Real})` qui renvoie un vecteur de _layers_, chacun contenant la courbe relative à une des périodes de retour contenues dans `T_values`, sur l'intervalle de durées `durations_range` et calculée à partir du modèle `model`.
La deuxième méthode fait appel à cette même fonction mais également à la fonction `get_layers_pointwise_estimations(data::IDFdata, T_values::Vector{<:Real}, durations::Vector{<:Real}, show_confidence_intervals::Bool)` qui qui renvoie un vecteur de _layers_ dans lesquels figurent les estimations ponctuelles des niveaux de retour, calculés à l'aide de la bibliothèque _Extremes.jl_. Si `show_confidence_intervals = true`, on représente également ls intervalles de confiance à 95% associés à ces estimations ponctuelles.

**Comment by jojal5** [comment]
C'est très astucieux ! J'approuve le tout :)

**Comment by AugustePaoli99** [comment]
OK, dans ce cas je ferme cette issue et je merge dans dev. Cependant j'ajoute l'[issue 128](https://github.com/JuliaExtremes/IDFCurves.jl/issues/128) pour le problème de l'absence de test unitaires pour les méthodes dans _plots.jl_.
